# default false
release_mode = false

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

# REDIS,FILE,COOKIE(COOKIE Default)
session_store = "REDIS"

# REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)
cache_store = "REDIS"

[app]
name = "AlertPlatform"

[server]
graceful = true
addr = ":8080"

[static]
# BINDATA,FILE(FILE Default)
type = "BINDATA"

[tmpl]
# PONGO2,TEMPLATE(TEMPLATE Default)
type = "PONGO2"
# BINDATA,FILE(FILE Default)
data = "BINDATA"
# PONGO2(template/pongo2),TEMPLATE(template)
dir = "public/views/"
# .html,.tpl
suffix = ".html"

[database]
name = "goweb_db"
user_name = "root"
pwd  = "ANtd79gRXzS"
host = "127.0.0.1"
port = "3306"